# Generated by Django 5.2.4 on 2025-08-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
